### PR TITLE
Auto layout

### PR DESCRIPTION
**Pull request by nitisha-neuroleap**
Changes in MenuViewController.xib in order to auto-layout the buttons.

### CODE REVIEW

**Comment by MiguelTepale** [comment]
Looks amazing! Please remove the added Navigation Controller and resolve the warnings in MainViewController.xib.

**Comment by MiguelTepale** [comment]
I'm seeing one more warning. I've attached a screen grab for your reference.

Screen Shot 2020-06-01 at 11 22 31 PM (2)

**Comment by nitisha-neuroleap** [comment]
It should be fixed now.

**Comment by MiguelTepale** [comment]
Thanks for getting back quickly. I have a question: You used ```alignment``` to create spacing between the leading chat bubble and leading view of UIButton. How do I know there's 22px of separation between those 2 views?

**Comment by nitisha-neuroleap** [comment]
The contents of the UIButton are left aligned, and I’m using the Title and
Image insets of the button to create the spacing. The image inset on the
left is 22px, and the title inset on the left is 38px, because it is
calculated from the edge of the button. So the space between the chat
bubble and “Chat” is 38-22 = 16px.

**Comment by MiguelTepale** [comment]
I didn't even know you could use the ```insets```, very cool approach. I'm going to assign you a special task that will implement the same view but without insets. I'll merge this PR and you'll create a separate branch that will not be merged while you create the view with only Auto Layout.
It'll be a good introduction to intermediate Auto Layout and Stack Views. 

Overall, good job on this feature! Looking forward to more of your PR's.

**Comment by nitisha-neuroleap** [comment]
I thought insets were a part of Auto Layout as that is all the posts on
stackoverflow used? But it’ll be interesting to learn a new approach!

**Comment by MiguelTepale** [comment]
> I thought insets were a part of Auto Layout as that is all the posts on stackoverflow used? But it’ll be interesting to learn a new approach!
> […](#)

> Typically, edge insets are used during view layout to modify the view’s frame.

In this case, you're just telling UIButton to create a certain distance for inset properties (title, image content). 

> Auto Layout dynamically calculates the size and position of all the views in your view hierarchy, based on constraints placed on those views.

Conversely, we're using constraints to adjust according to different screen sizes.

Your approach is fine. You would just benefit from also learning how to do it with only Auto Layout. It's good to know different ways on how to layout views since every project will take a different approach.

**Comment by MiguelTepale** [comment]
Sorry, one last request. You can tidy up the directory in ```MenuViewController.xib```. I've attached a screen grab of how I approach naming Storyboard items. This is very beneficial especially when you're debugging views and viewing relationships between two views.

Screen Shot 2020-06-02 at 1 11 53 AM

**Comment by nitisha-neuroleap** [comment]
I don’t have that many elements in the hierarchy, but I renamed what I
have.

**Pull request merged**
